/*******************************************************************************
	Generated by: DLL to C version 3.48
	Date: 2019-8-8
	Description: The implementation code for onetap.dll.
	Website: http://www.dll-decompiler.com
	Technical Support: support@dll-decompiler.com
*******************************************************************************/

#include "stdafx.h"
#include "Onetap.h"


HMODULE g_hOnetap;
BOOL (WINAPI *Onetap_DllEntryPoint)(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpReserved);

extern UCHAR Onetap_text[0x43000];
extern UCHAR Onetap_rdata[0x4000];
extern UCHAR Onetap_data[0x187000];

__declspec(align(16)) stOnetap Onetap;

void* __stdcall Onetap_RVA(DWORD rvaAddr)
{
	return (UCHAR*)&Onetap + rvaAddr;
}

BOOL Onetap_Init()
{
	HMODULE hDll;
	DWORD oldProtect;
	void (*fInitData)(HMODULE,void*,void*);

	g_hOnetap = GetModuleHandle(0);

	oldProtect = PAGE_EXECUTE_READWRITE;
	VirtualProtect(&Onetap,sizeof(Onetap),PAGE_EXECUTE_READWRITE,&oldProtect);

	memcpy(&Onetap.Text,&Onetap_text,sizeof(Onetap_text));
	memcpy(&Onetap.Rdata,&Onetap_rdata,sizeof(Onetap_rdata));
	memcpy(&Onetap.Data,&Onetap_data,sizeof(Onetap_data));

	hDll = ::LoadLibraryA("KERNEL32.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"KERNEL32.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Onetap_VA(0x10044000) = ::GetProcAddress(hDll,"GetModuleHandleA");
	if(!*(FARPROC*)Onetap_VA(0x10044000))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044004) = ::GetProcAddress(hDll,"GetProcAddress");
	if(!*(FARPROC*)Onetap_VA(0x10044004))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044008) = ::GetProcAddress(hDll,"Sleep");
	if(!*(FARPROC*)Onetap_VA(0x10044008))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x1004400C) = ::GetProcAddress(hDll,"GetCurrentProcess");
	if(!*(FARPROC*)Onetap_VA(0x1004400C))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044010) = ::GetProcAddress(hDll,"VirtualAlloc");
	if(!*(FARPROC*)Onetap_VA(0x10044010))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044014) = ::GetProcAddress(hDll,"DisableThreadLibraryCalls");
	if(!*(FARPROC*)Onetap_VA(0x10044014))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044018) = ::GetProcAddress(hDll,"LoadLibraryA");
	if(!*(FARPROC*)Onetap_VA(0x10044018))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x1004401C) = ::GetProcAddress(hDll,"GetSystemTimeAsFileTime");
	if(!*(FARPROC*)Onetap_VA(0x1004401C))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044020) = ::GetProcAddress(hDll,"GetCurrentThreadId");
	if(!*(FARPROC*)Onetap_VA(0x10044020))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044024) = ::GetProcAddress(hDll,"GetCurrentProcessId");
	if(!*(FARPROC*)Onetap_VA(0x10044024))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044028) = ::GetProcAddress(hDll,"QueryPerformanceCounter");
	if(!*(FARPROC*)Onetap_VA(0x10044028))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x1004402C) = ::GetProcAddress(hDll,"IsDebuggerPresent");
	if(!*(FARPROC*)Onetap_VA(0x1004402C))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044030) = ::GetProcAddress(hDll,"IsProcessorFeaturePresent");
	if(!*(FARPROC*)Onetap_VA(0x10044030))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044034) = ::GetProcAddress(hDll,"TerminateProcess");
	if(!*(FARPROC*)Onetap_VA(0x10044034))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044038) = ::GetProcAddress(hDll,"SetUnhandledExceptionFilter");
	if(!*(FARPROC*)Onetap_VA(0x10044038))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x1004403C) = ::GetProcAddress(hDll,"UnhandledExceptionFilter");
	if(!*(FARPROC*)Onetap_VA(0x1004403C))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044040) = ::GetProcAddress(hDll,"InitializeSListHead");
	if(!*(FARPROC*)Onetap_VA(0x10044040))
		return FALSE;

	hDll = ::LoadLibraryA("MSVCP140.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"MSVCP140.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Onetap_VA(0x10044048) = ::GetProcAddress(hDll,"?_Xlength_error@std@@YAXPBD@Z");
	if(!*(FARPROC*)Onetap_VA(0x10044048))
		return FALSE;

	hDll = ::LoadLibraryA("VCRUNTIME140.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"VCRUNTIME140.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Onetap_VA(0x10044050) = ::GetProcAddress(hDll,"memmove");
	if(!*(FARPROC*)Onetap_VA(0x10044050))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044054) = ::GetProcAddress(hDll,"__std_type_info_destroy_list");
	if(!*(FARPROC*)Onetap_VA(0x10044054))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044058) = ::GetProcAddress(hDll,"memcpy");
	if(!*(FARPROC*)Onetap_VA(0x10044058))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x1004405C) = ::GetProcAddress(hDll,"__CxxFrameHandler3");
	if(!*(FARPROC*)Onetap_VA(0x1004405C))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044060) = ::GetProcAddress(hDll,"__std_exception_copy");
	if(!*(FARPROC*)Onetap_VA(0x10044060))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044064) = ::GetProcAddress(hDll,"__std_exception_destroy");
	if(!*(FARPROC*)Onetap_VA(0x10044064))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044068) = ::GetProcAddress(hDll,"_CxxThrowException");
	if(!*(FARPROC*)Onetap_VA(0x10044068))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x1004406C) = ::GetProcAddress(hDll,"_except_handler4_common");
	if(!*(FARPROC*)Onetap_VA(0x1004406C))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044070) = ::GetProcAddress(hDll,"memset");
	if(!*(FARPROC*)Onetap_VA(0x10044070))
		return FALSE;

	hDll = ::LoadLibraryA("api-ms-win-crt-runtime-l1-1-0.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"api-ms-win-crt-runtime-l1-1-0.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Onetap_VA(0x10044088) = ::GetProcAddress(hDll,"_crt_atexit");
	if(!*(FARPROC*)Onetap_VA(0x10044088))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x1004408C) = ::GetProcAddress(hDll,"_initterm_e");
	if(!*(FARPROC*)Onetap_VA(0x1004408C))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044090) = ::GetProcAddress(hDll,"_register_onexit_function");
	if(!*(FARPROC*)Onetap_VA(0x10044090))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044094) = ::GetProcAddress(hDll,"_initialize_onexit_table");
	if(!*(FARPROC*)Onetap_VA(0x10044094))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044098) = ::GetProcAddress(hDll,"_initialize_narrow_environment");
	if(!*(FARPROC*)Onetap_VA(0x10044098))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x1004409C) = ::GetProcAddress(hDll,"_configure_narrow_argv");
	if(!*(FARPROC*)Onetap_VA(0x1004409C))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x100440A0) = ::GetProcAddress(hDll,"terminate");
	if(!*(FARPROC*)Onetap_VA(0x100440A0))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x100440A4) = ::GetProcAddress(hDll,"_execute_onexit_table");
	if(!*(FARPROC*)Onetap_VA(0x100440A4))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x100440A8) = ::GetProcAddress(hDll,"_cexit");
	if(!*(FARPROC*)Onetap_VA(0x100440A8))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x100440AC) = ::GetProcAddress(hDll,"_invalid_parameter_noinfo_noreturn");
	if(!*(FARPROC*)Onetap_VA(0x100440AC))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x100440B0) = ::GetProcAddress(hDll,"_initterm");
	if(!*(FARPROC*)Onetap_VA(0x100440B0))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x100440B4) = ::GetProcAddress(hDll,"_seh_filter_dll");
	if(!*(FARPROC*)Onetap_VA(0x100440B4))
		return FALSE;

	hDll = ::LoadLibraryA("api-ms-win-crt-heap-l1-1-0.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"api-ms-win-crt-heap-l1-1-0.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)Onetap_VA(0x10044078) = ::GetProcAddress(hDll,"_callnewh");
	if(!*(FARPROC*)Onetap_VA(0x10044078))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x1004407C) = ::GetProcAddress(hDll,"malloc");
	if(!*(FARPROC*)Onetap_VA(0x1004407C))
		return FALSE;
	*(FARPROC*)Onetap_VA(0x10044080) = ::GetProcAddress(hDll,"free");
	if(!*(FARPROC*)Onetap_VA(0x10044080))
		return FALSE;

	*(FARPROC*)&fInitData = (FARPROC)&Onetap_InitData[0];
	fInitData(g_hOnetap,Onetap_RVA,NULL);

	*(FARPROC*)&Onetap_DllEntryPoint = (FARPROC)Onetap_VA(0x10041058);
	return TRUE;
}

