/*******************************************************************************
	Generated by: DLL to C version 3.48
	Date: 2019-8-8
	Description: The declaration of functions and variables for onetap.dll.
	Website: http://www.dll-decompiler.com
	Technical Support: support@dll-decompiler.com
*******************************************************************************/

#if !defined(_ONETAP_SUPP_H_001D1000_INCLUDED_)
#define _ONETAP_SUPP_H_001D1000_INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000


#include <windows.h>

#pragma pack(push)
#pragma pack(1)

__declspec(align(16)) struct stOnetap
{
	UCHAR Header[0x1000];
	UCHAR Text[0x43000];
	UCHAR Rdata[0x4000];
	UCHAR Data[0x187000];
	UCHAR Rsrc[0x1000];
	UCHAR Reloc[0x1000];
};

#pragma pack(pop)

__declspec(align(16)) extern stOnetap Onetap;

/* Data for initialization. */
extern UCHAR Onetap_InitData[0x1A2A];

extern HMODULE g_hOnetap;

/*
	Description: Access any address in the DLL.
	Parameters:
		rvaAddr: The RVA address you want to access.
*/
void* __stdcall Onetap_RVA(DWORD rvaAddr);

#define Onetap_VA(vaAddr) Onetap_RVA((vaAddr) - 0x10000000)


#endif // !defined(_ONETAP_SUPP_H_001D1000_INCLUDED_)